### ISSUE TITLE
Building for python 3.6

### ISSUE THREAD

**Issue by spockNinja** [NoRedInk/make-lambda-package#7]
This project looks awesome. We are currently using Zappa, but aren't satisfied with it's bloat or packaging behavior.

One big thing missing for us is the ability to package a python 3.6 lambda application.

I believe it would be a pretty simple addition, but want to make sure it would be a welcome PR, and that my approach would be acceptable.

The only two changes I had to make locally were:

https://github.com/NoRedInk/make-lambda-package/blob/master/make_lambda_package/deps.py#L58

and 

https://github.com/NoRedInk/make-lambda-package/blob/master/make_lambda_package/archive.py#L36

The rest seemed to work just fine. So I think it would be safe to put the python version behind another cli argument that defaults to 'python2.7' and also allows 'python3.6'. That argument could then be passed to `build_deps` and `make_archive`.

If a PR with that approach would be welcome, I would be happy to whip it up. Thanks!

**Comment by ento** [comment]
Thanks for reaching out! The approach sounds good to me.

`--runtime` might be a fitting name for the flag, though I'll leave it up to you :)

**Comment by spockNinja** [comment]
Awesome! `--runtime` sounds perfect. I'll try to get that whipped up in short order.
